# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\"0\n\x10\x45mbeddingRequest\x12\x1c\n\x14\x65mbeddingsListBinary\x18\x01 \x01(\x0c\"1\n\x11\x45mbeddingResponse\x12\x1c\n\x14\x65mbeddingsListBinary\x18\x01 \x01(\x0c\x32\xa6\x01\n\x10\x45mbeddingService\x12P\n\x13\x43\x61lculateEmbeddings\x12\x1b.embedding.EmbeddingRequest\x1a\x1c.embedding.EmbeddingResponse\x12@\n\x04\x45\x63ho\x12\x1b.embedding.EmbeddingRequest\x1a\x1b.embedding.EmbeddingRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGREQUEST']._serialized_start=30
  _globals['_EMBEDDINGREQUEST']._serialized_end=78
  _globals['_EMBEDDINGRESPONSE']._serialized_start=80
  _globals['_EMBEDDINGRESPONSE']._serialized_end=129
  _globals['_EMBEDDINGSERVICE']._serialized_start=132
  _globals['_EMBEDDINGSERVICE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
